CREATE OR REPLACE FUNCTION etl.clean(v TEXT) RETURNS TEXT AS $$
    SELECT NULLIF(NULLIF(TRIM(v), ''), 'NULL');
$$ LANGUAGE SQL IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.try_int(v TEXT) RETURNS INT AS $$
BEGIN
    RETURN etl.clean(v)::int;
EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION etl.try_num(v TEXT) RETURNS NUMERIC AS $$
BEGIN
    RETURN REPLACE(etl.clean(v), ',', '.')::numeric;
EXCEPTION WHEN others THEN
    RETURN NULL;
END;
$$ LANGUAGE plpgsql IMMUTABLE;